### ISSUE TITLE
Request for to have access to do research on POLID dataset

### ISSUE THREAD

**Issue by Shabnam-Maraghechi** [peyman-alv/healthcare-fairness-measurement#1]
Hi Peyman,

Sale no mobarak! I hope you are well.

My name is Shabnam Maraghechi, I'm a MSc Big Data Science student in Queen Mary University of London. I came across your work about hate speech detection using BERT model on a Farsi dataset. Atm, I'm doing my thesis in the same topic but different problem and I wonder if there is possible to have access to the POLID dataset that you guys generated so I can work on it as well?
I plan to work on a few datasets and I appreciate your help in this matter.

Anyhow, enjoy Nowruz!
Looking forward to hearing from you.

Kind regards,
Shabnam

**Comment by peyman-alv** [comment]
Hello Shabnam,

Thank you for reaching out to me, and I'm glad to hear that you are interested in my work. I would be happy to share the POLID dataset with you. Please send me your email address, and I will share the dataset with you.

Best regards,
Peyman

**Comment by Shabnam-Maraghechi** [comment]
Hi Peyman,

Thank you so much for your reply. Sure thing, here is my email address: shabnam.maraghechi@gmail.com

I appreciate your time.

many thanks,
Shabnam

**Comment by peyman-alv** [comment]
I shared the dataset with you.

Happy Nowrouz!
